#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn format
git add .
npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "test,lint,typecheck,build" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "yarn test -- --watch=false" \
    "yarn lint" \
    "yarn typecheck" \
    "yarn build"